SELECT CITY , LENGTH(CITY) AS Longest_city
FROM STATION
ORDER BY LENGTH(CITY) DESC , CITY DESC
LIMIT 1;

SELECT CITY , LENGTH(CITY) AS Shortest_city
FROM STATION
ORDER BY LENGTH(CITY) ASC, CITY ASC
LIMIT 1;
